modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://github.com/McJtyMods/RFToolsStorage/issues"
displayURL="http://github.com/McJtyMods/RFToolsStorage/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="McJty"

[[mods]]
modId="rftoolsstorage"
version="${file.jarVersion}"
displayName="RFToolsStorage"
#updateJSONURL="http://myurl.me/" #optional
description='''
Everything related to storage
'''
[[dependencies.rftoolsstorage]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rftoolsstorage]]
    modId="mcjtylib"
    mandatory=true
    versionRange="[1.15-4.1.7,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.rftoolsstorage]]
    modId="rftoolsbase"
    mandatory=true
    versionRange="[1.15-1.1.6,)"
    ordering="AFTER"
    side="BOTH"